[package]
name = "databend-cmds"
version = "0.1.0"
description = "databend command line tools"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[features]
default = ["simd"]
memory-profiling = ["databend-meta/memory-profiling", "databend-query/memory-profiling", "common-base/memory-profiling"]
simd = ["databend-meta/simd", "databend-query/simd"]
tokio-console = [
    "databend-meta/tokio-console",
    "databend-query/io-uring",
    "common-base/tracing",
    "common-tracing/console",
]
io-uring = [
    "databend-meta/io-uring",
    "databend-query/io-uring",
    "common-meta-store/io-uring",
    "common-meta-sled-store/io-uring",
    "common-meta-raft-store/io-uring",
]

[dependencies]
# Workspace dependencies
common-base = { path = "../common/base" }
common-exception = { path = "../common/exception" }
common-grpc = { path = "../common/grpc" }
common-macros = { path = "../common/macros" }
common-meta-api = { path = "../common/meta/api" }
common-meta-app = { path = "../common/meta/app" }
common-meta-embedded = { path = "../common/meta/embedded" }
common-meta-grpc = { path = "../common/meta/grpc" }
common-meta-raft-store = { path = "../common/meta/raft-store" }
common-meta-sled-store = { path = "../common/meta/sled-store" }
common-meta-store = { path = "../common/meta/store" }
common-meta-types = { path = "../common/meta/types" }
common-metrics = { path = "../common/metrics" }
common-tracing = { path = "../common/tracing" }
databend-meta = { path = "../meta/service" }
databend-query = { path = "../query/service" }

# Crates.io dependencies
anyhow = "1.0.58"
clap = { version = "3.2.5", features = ["derive", "env"] }
sentry = "0.27.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio-stream = "0.1.9"
tonic = "0.7.2"
tracing = "0.1.35"
url = "2.2.2"

openraft = { git = "https://github.com/datafuselabs/openraft", rev = "v0.7.0-alpha.2" }

[[bin]]
name = "databend-meta"
path = "targets/meta/main.rs"
doctest = false
test = false

[[bin]]
name = "databend-metabench"
path = "targets/metabench.rs"
doctest = false
test = false

[[bin]]
name = "databend-metactl"
path = "targets/metactl/main.rs"
doctest = false
test = false

[[bin]]
name = "databend-query"
path = "targets/query.rs"
doctest = false
test = false
