[package]
name = "common-metrics"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-exception = { path = "../exception" }
common-infallible = { path = "../infallible" }
common-tracing = { path = "../tracing" }

# Crates.io dependencies
metrics = "0.18.1"
metrics-exporter-prometheus = { version = "0.9.0", default-features = false }
once_cell = "1.10.0"
prometheus-parse = "0.2.2"
serde = { version = "1.0.136", features = ["derive"] }

[dev-dependencies.tokio]
default-features = false
features = ["io-util", "net", "sync", "rt-multi-thread", "macros"]
version = "1.17.0"
