name: "Test sqllogic Standalone"
description: "Running sqllogic tests in standalone mode"
inputs:
  profile:
    description: "The profile for this test"
    required: true
    default: "debug"
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        profile: ${{ inputs.profile }}
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}
        source: s3

    - name: Install python dependences
      shell: bash
      run: |
        pip3 install --user boto3 "moto[all]" yapf shfmt-py mysql-connector pymysql six PyHamcrest requests environs fire

    - name: Run sqllogic Tests with Standalone mode with embedded meta-store
      shell: bash
      run: |
        bash ./scripts/ci/ci-run-sqllogic-tests.sh

    - name: Upload failure
      if: failure()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-sqllogic-standalone-linux
