queue_rules:
  - name: shared_queue
    # Enable speculative_checks and batch size so that we can rollup
    # enqueued PRs at the same time instead of one by one.
    #
    # Reference: https://docs.mergify.com/actions/queue/#id4
    speculative_checks: 2
    batch_size: 5
    conditions:
      - "#approved-reviews-by>=2"

      # Must write expected checks explicitly
      # Reference: https://docs.mergify.com/conditions/#validating-all-status-checks
      # We only require linux checks to pass
      - check-success=check
      - check-success~=^build_(aarch64|x86_64)_musl$
      - check-success=test_unit
      - check-success=test_metactl
      - check-success=test_stateless_standalone_linux
      - check-success=test_stateless_cluster_linux
      - check-success=test_stateful_standalone_linux
      - check-success=test_sqllogic_standalone_linux

pull_request_rules:
  # Push PR into queue when it passes all checks
  - name: put approved pr to queue
    conditions:
      - "#approved-reviews-by>=2"
      - -draft
      - check-success=check
      - check-success~=^build_(aarch64|x86_64)_musl$
      - check-success=test_unit
      - check-success=test_metactl
      - check-success=test_stateless_standalone_linux
      - check-success=test_stateless_cluster_linux
      - check-success=test_stateful_standalone_linux
      - check-success=test_sqllogic_standalone_linux
    actions:
      queue:
        name: shared_queue

  # If there is a conflict in an approved PR, ping the author.
  - name: ping author on conflicts
    conditions:
      - conflict
      - -draft
      - "#approved-reviews-by >= 2"
    actions:
      comment:
        message: |
          This pull request has merge conflicts that must be resolved before it can be merged. @{{author}} please update it 🙏.

  # Welcome new contributors
  - name: Welcome new contributor
    conditions:
      - author!=Mergify
    actions:
      comment:
        message: |
          Thanks for the contribution!
          I have applied any labels matching special text in your PR Changelog.

          Please review the labels and make any necessary changes.

  # Check if PR description contains CLA
  - name: Check PR description
    conditions:
      - author!=Mergify
      - -draft
      - '-body~=I hereby agree to the terms of the CLA available at: https:\/\/databend\.rs\/dev\/policies\/cla\/'
      - "-body~=Summary"
    actions:
      comment:
        message: |
          This pull request's description is not fulfill the requirements. @{{author}} please update it 🙏.

          The description should contain the following:

          ```
          I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

          ## Summary

          Summary about this PR

          Fixes #issue
          ```

  # Check if PR title contain valid tags
  - name: Check PR title
    conditions:
      - author!=Mergify
      - -draft
      - '-title~=^(feat|fix|refactor|ci|build|docs|website|chore)(\(.*\))?:'
    actions:
      comment:
        message: |
          This pull request's title is not fulfill the requirements. @{{author}} please update it 🙏.

          The title should contain one if the following tags:

          - `feat`: this PR introduces a new feature to the codebase
          - `fix`: this PR patches a bug in codebase
          - `refactor`: this PR changes the code base without new features or bugfix
          - `ci|build`: this PR changes build/testing/ci steps
          - `docs|website`: this PR changes the documents or websites
          - `chore`: this PR only has small changes that no need to record

  # Assign pr label based of tags
  - name: label on New Feature
    conditions:
      - 'title~=^(feat)(\(.*\))?:'
    actions:
      label:
        add:
          - pr-feature
  - name: label on Bug Fix
    conditions:
      - 'title~=^(fix)(\(.*\))?:'
    actions:
      label:
        add:
          - pr-bugfix
  - name: label on Refactor
    conditions:
      - 'title~=^(refactor)(\(.*\))?:'
    actions:
      label:
        add:
          - pr-refactor
  - name: label on Build/Testing/CI
    conditions:
      - 'title~=^(ci|build)(\(.*\))?:'
    actions:
      label:
        add:
          - pr-build
  - name: label on Documentation
    conditions:
      - 'title~=^(docs|website)(\(.*\))?:'
    actions:
      label:
        add:
          - pr-doc
  - name: label on Not for changelog
    conditions:
      - 'title~=^(chore)(\(.*\))?:'
    actions:
      label:
        add:
          - pr-chore
