extends: default

ignore: |
  build/
  target/

rules:
  # 100 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 100
    level: warning
  braces: disable
  brackets: disable
  document-start: disable
  truthy:
    check-keys: false
