[workspace]
members = [
    # Cmds
    "src/cmds",

    # Common
    "src/common/arrow",
    "src/common/base",
    "src/common/building",
    "src/common/cache",
    "src/common/catalog",
    "src/common/codegen",
    "src/common/config",
    "src/common/contexts",
    "src/common/datablocks",
    "src/common/datavalues",
    "src/common/exception",
    "src/common/expression",
    "src/common/formats",
    "src/common/functions",
    "src/common/functions-v2",
    "src/common/grpc",
    "src/common/hashtable",
    "src/common/hive-meta-store",
    "src/common/http",
    "src/common/io",
    "src/common/macros",
    "src/common/management",
    "src/common/metrics",
    "src/common/planners",
    "src/common/proto-conv",
    "src/common/protos",
    "src/common/streams",
    "src/common/tracing",
    "src/common/users",
    "src/common/storage",
    "src/common/storages/hive",
    "src/common/storages/index",
    "src/common/fuse-meta",

    # Query
    "src/query/ast",
    # databend-query
    "src/query/service",

    # Meta
    "src/meta/api",
    "src/meta/app",
    "src/meta/embedded",
    "src/meta/raft-store",
    "src/meta/sled-store",
    "src/meta/store",
    "src/meta/types",
    # databend-meta
    "src/meta/service",

    # Hack
    # This crate is used to hack our cargo.lock to resovle CVEs and so on.
    "src/workspace-hack",
]

[profile.release]
debug = 1
lto = "thin"
overflow-checks = false
codegen-units = 1       # Reduce number of codegen units to increase optimizations.

[profile.release.package]
arrow2 = { codegen-units = 4 }
common-functions = { codegen-units = 16 }
databend-query = { codegen-units = 4 }

[profile.bench]
debug = true
overflow-checks = false

[profile.dev]
split-debuginfo = "unpacked"
overflow-checks = false

[profile.test]
opt-level = 0
debug = 0
codegen-units = 16
lto = false
incremental = true
debug-assertions = true
overflow-checks = true
rpath = false

[profile.dev.package]
addr2line = { opt-level = 3 }
adler = { opt-level = 3 }
gimli = { opt-level = 3 }
miniz_oxide = { opt-level = 3 }
object = { opt-level = 3 }
rustc-demangle = { opt-level = 3 }

[patch.crates-io]
parquet2 = { version = "0.14.1", optional = true, git = "https://github.com/datafuse-extras/parquet2", rev = "3a468fc3c4" }
