[package]
name = "common-mem-allocator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../base" }
common-infallible = { path = "../infallible" }
libc = { version = "0.2", optional = true }

parking_lot = "0.12.0"
tikv-jemalloc-ctl = { version = "0.4", optional = true }
tikv-jemalloc-sys = { version = "0.4.3" }

[dev-dependencies]
common-macros = { path = "../macros" }

[features]
memory-profiling = [
    "tikv-jemalloc-ctl",
    "libc",
    "tikv-jemalloc-sys/stats",
    "tikv-jemalloc-sys/profiling",
    "tikv-jemalloc-sys/unprefixed_malloc_on_supported_platforms",
]
