[package]
name = "common-storages-hive"
version = "0.1.0"
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-datablocks = { path = "../../../common/datablocks" }
common-datavalues = { path = "../../../common/datavalues" }
common-exception = { path = "../../../common/exception" }
common-fuse-meta = { path = "../../../common/fuse-meta" }
common-hive-meta-store = { path = "../../../common/hive-meta-store" }
common-meta-app = { path = "../../../meta/app" }
common-meta-types = { path = "../../../meta/types" }
common-pipeline-core = { path = "../../../common/pipeline/core" }
common-pipeline-sources = { path = "../../../common/pipeline/sources" }
common-planners = { path = "../../../common/planners" }
common-storages-index = { path = "../index" }
common-storages-util = { path = "../util" }

async-recursion = "1.0.0"
async-trait = "0.1.56"
futures = "0.3.21"
opendal = { version = "0.13.0", features = ["layers-retry"] }
serde = { version = "1.0.137", features = ["derive"] }
thrift = "0.15.0"
tracing = "0.1.35"
typetag = "0.1.8"
