[package]
name = "databend-fuzz"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "fuzz_parse_sql"
path = "fuzz_targets/fuzz_parse_sql.rs"
doctest = false
test = false

[dependencies]
common-ast = { path = "../../common/ast" }

afl = "0.12"
arbitrary = "1.1.3"
