[package]
name = "common-meta-store"
version = "0.1.0"
description = "MetaStore is impl with either a local embedded meta store, or a grpc-client of metasrv"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies

# Crates.io dependencies

[dev-dependencies]
