[package]
name = "common-pipeline-sources"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../base" }
common-catalog = { path = "../../catalog" }
common-datablocks = { path = "../../datablocks" }
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../exception" }
common-formats = { path = "../../formats" }
common-io = { path = "../../io" }
common-meta-types = { path = "../../meta/types" }
common-pipeline-core = { path = "../core" }
common-storage = { path = "../../storage" }
common-streams = { path = "../../streams" }

async-trait = { git = "https://github.com/datafuse-extras/async-trait", rev = "f0b0fd5" }
chrono = "0.4.19"
futures = "0.3.21"
futures-util = "0.3.21"
itertools = "0.10.3"
num_cpus = "1.13.1"
once_cell = "1.12.0"
opendal = { version = "0.11.4", features = ["retry"] }
parking_lot = "0.12.1"
petgraph = "0.6.2"
serde = { version = "1.0.137", features = ["derive"] }
time = "0.3.10"
