[package]
name = "common-fuse-meta"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[features]

[dependencies]
common-arrow = { path = "../arrow" }
common-base = { path = "../base" }
common-cache = { path = "../cache" }
common-config = { path = "../config" }
common-datablocks = { path = "../../query/datablocks" }
common-datavalues = { path = "../../query/datavalues" }
common-exception = { path = "../exception" }
common-metrics = { path = "../metrics" }

serde = { version = "1.0.137", features = ["derive"] }
