[package]
name = "common-pipeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../base" }
common-config = { path = "../config" }
common-datablocks = { path = "../datablocks" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../exception" }
common-grpc = { path = "../grpc" }
common-hashtable = { path = "../hashtable" }
common-meta-types = { path = "../meta/types" }
common-storage = { path = "../storage" }
common-tracing = { path = "../tracing" }
common-users = { path = "../users" }

async-trait = "0.1.56"
bumpalo = "3.10.0"
clap = { version = "3.2.5", features = ["derive", "env"] }
futures = "0.3.21"
futures-util = "0.3.21"
itertools = "0.10.3"
num_cpus = "1.13.1"
once_cell = "1.12.0"
opendal = { version = "0.11.0", features = ["retry"] }
parking_lot = "0.12.1"
petgraph = "0.6.2"
semver = "1.0.10"
serde = { version = "1.0.137", features = ["derive"] }
serfig = "0.0.2"
time = "0.3.10"
