name: Auto tag for nightly release

on:
  schedule:
    # Release at 00:00 UTC+8
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Bump version and push tag
        id: generated-tag
        uses: actions/github-script@v6
        with:
          script: |
            let tag = "${{ steps.get-latest-tag.outputs.tag }}";
            let result = /v(\d+)\.(\d+)\.(\d+)/g.exec(tag);
            if (result === null) {
              console.log("invalid tag, ignoring");
              return
            }

            let major = result[1];
            let minor = result[2];
            let patch = (parseInt(result[3]) + 1).toString();
            let next_tag = `v${major}.${minor}.${patch}-nightly`;

            core.setOutput('tag', next_tag)
      - uses: actions-ecosystem/action-push-tag@v1
        if: ${{ steps.generated-tag.outputs.tag }}
        with:
          tag: ${{ steps.generated-tag.outputs.tag }}
