name: Developing

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"
      - "scripts/setup/**"
      - ".devcontainer/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  BUILD_PROFILE: debug

jobs:
  check:
    runs-on: [self-hosted, x64, Linux]
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build_macos:
    name: "build_macos(optional)"
    runs-on: macos-11
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_macos
        with:
          target: ${{ matrix.target }}
          profile: debug

  build_linux:
    runs-on: [self-hosted, x64, Linux, development]
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        with:
          target: ${{ matrix.target }}
          profile: debug


  build_musl:
    runs-on: [self-hosted, x64, Linux, development]
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        with:
          target: ${{ matrix.target }}
          profile: debug

  test_unit:
    runs-on: [self-hosted, x64, Linux]
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/test_unit
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  test_metactl:
    runs-on: [self-hosted, x64, Linux, development]
    needs: build_linux
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_metactl

  test_compat:
    runs-on: [self-hosted, x64, Linux, development]
    needs: build_linux
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_compat

  test_meta_cluster:
    runs-on: [self-hosted, x64, Linux, development]
    needs: build_linux
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_meta_cluster

  test_stateless_standalone_linux:
    runs-on: [self-hosted, x64, Linux, development]
    needs: build_linux
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_standalone_linux

  # https://github.com/datafuselabs/databend/issues/5287
  # test_stateless_standalone_macos:
  #  runs-on: macos-11
  #  needs: build_macos
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: ./.github/actions/test_stateless_standalone_macos

  test_stateless_cluster_linux:
    runs-on: [self-hosted, x64, Linux, development]
    needs: build_linux
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_cluster_linux

  test_stateless_cluster_macos:
    name: "test_stateless_cluster_macos(optional)"
    runs-on: macos-11
    needs: build_macos
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_cluster_macos

  test_sqllogic_standalone_macos:
    name: "test_sqllogic_standalone_macos(optional)"
    runs-on: macos-11
    needs: build_macos
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_sqllogic_standalone_macos

  test_sqllogic_standalone_linux:
    runs-on: [self-hosted, x64, Linux, development]
    needs: build_linux
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_sqllogic_standalone_linux

  test_stateful_standalone_linux:
    runs-on: [self-hosted, x64, Linux, development]
    needs: build_linux
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_standalone_linux

  build_linux_hive:
    runs-on: [self-hosted, x64, Linux, development]
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build_linux_hive
        with:
          target: ${{ matrix.target }}
          profile: debug

  test_stateful_hive_standalone:
    runs-on: [self-hosted, x64, Linux, development]
    needs: build_linux_hive
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_hive_standalone
