name: Platform

on:
  push:
    branches:
      - main
    paths:
      - "scripts/setup/**"

jobs:
  build_dev_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian
          - alpine
        platform:
          - amd64
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get rust toolchain version
        id: toolchain_version
        run: |
          version=$(awk -F'[ ="]+' '$1 == "channel" { print $2 }' scripts/setup/rust-toolchain.toml)
          echo "::set-output name=RUST_TOOLCHAIN::${version}"

      - name: Build and publish databend build base image
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: datafuselabs/build-tool:base-${{ matrix.distro }}-${{ matrix.platform }}, datafuselabs/build-tool:base-${{ matrix.distro }}-${{ matrix.platform }}-${{ steps.toolchain_version.outputs.RUST_TOOLCHAIN }}
          context: .
          target: build-base
          file: ./docker/build-tool/${{ matrix.distro }}/Dockerfile

      - name: Build and publish databend multiarch image
        id: docker_build_multiarch
        if: ${{ matrix.distro == 'debian' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: datafuselabs/build-tool:multiarch, datafuselabs/build-tool:multiarch-${{ steps.toolchain_version.outputs.RUST_TOOLCHAIN }}
          context: .
          target: multiarch
          file: ./docker/build-tool/${{ matrix.distro }}/Dockerfile

      - name: Build and publish databend development image
        id: docker_build_development
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: datafuselabs/build-tool:dev-${{ matrix.distro }}-${{ matrix.platform }}, datafuselabs/build-tool:dev-${{ matrix.distro }}-${{ matrix.platform }}-${{ steps.toolchain_version.outputs.RUST_TOOLCHAIN }}
          context: .
          target: dev
          file: ./docker/build-tool/${{ matrix.distro }}/Dockerfile
