name: "Test Stateless Cluster MacOS"
description: "Running stateless tests in cluster mode"
inputs:
  profile:
    description: "The profile for this test"
    required: true
    default: "debug"
  target:
    description: ""
    required: true
    default: "x86_64-apple-darwin"
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        profile: ${{ inputs.profile }}
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}

    - name: Install mysql client for macos-11
      shell: bash
      run: |
        brew install mysql

    - name: Install python dependences
      shell: bash
      run: |
        pip3 install --user boto3 "moto[all]" yapf shfmt-py mysql-connector pymysql sqlalchemy clickhouse_driver

    - name: Run Stateless Tests with Cluster mode
      shell: bash
      run: |
        bash ./scripts/ci/ci-run-stateless-tests-cluster.sh

    - name: Upload failure
      if: failure()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-stateless-cluster-macos
